### ISSUE TITLE
flac encoder error

### ISSUE THREAD

**Issue by unklebonehead** [Iunusov/ShoutVST#6]
Got this error while trying to build on Ubuntu Studio 21.04

ST/ShoutVSTEncoderFLAC.h:4:10: fatal error: FLAC++/encoder.h: No such file or directory
    4 | #include <FLAC++/encoder.h>

**Comment by afalout** [comment]
You need to install FLAC++ that includes encoder.h file (that has to be in your includes path of course)
